apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
  namespace: secure-platform
data:
  SIGNALING_PORT: "8443"
  SIGNALING_API_URL: "http://signaling-svc:8443"
  ENVIRONMENT: "production"
