apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend-pdb
  namespace: secure-platform
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dashboard-backend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: signaling-pdb
  namespace: secure-platform
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: signaling
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-pdb
  namespace: secure-platform
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dashboard-frontend
