apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
  namespace: secure-platform
type: Opaque
stringData:
  DATABASE_URL: "postgresql://platform_admin:ChangeInProductionPassword123!@postgres-svc:5432/remote_access"
  JWT_SECRET: "ChangeInProductionJwtSecretKey2026!"
  SIGNALING_API_KEY: "ChangeInProductionSignalingSecretKey2026!"
  AGENT_AUTH_TOKEN: "ChangeInProductionAgentToken123!"
