apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-backend
  namespace: secure-platform
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: signaling
  namespace: secure-platform
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-frontend
  namespace: secure-platform
spec:
  replicas: 1
